//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public long SequenceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public int CountryID { get; set; }
        public int HotelCategoryID { get; set; }
        public string Website { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool AppearInHotelAvailability { get; set; }
        public bool AppearInWeb { get; set; }
        public bool CostEquPrice { get; set; }
        public string Email { get; set; }
        public Nullable<int> AccountNoID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> CostCenterID { get; set; }
        public Nullable<int> AgentAccountantID { get; set; }
        public Nullable<int> IncomeAccountID { get; set; }
        public string IncomeAccountName { get; set; }
        public Nullable<int> PurchaseAccountID { get; set; }
        public string PurchaseAccountName { get; set; }
        public Nullable<int> HotelGroupID { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
