//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int HotelID { get; set; }
        public int OperatorID { get; set; }
        public long SequanceID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> DocumnetID { get; set; }
        public string GuestName { get; set; }
        public Nullable<int> NumberOfAdults { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string Contact { get; set; }
        public Nullable<int> TermsAndConditionID { get; set; }
        public Nullable<int> HotelRservationAccountID { get; set; }
        public string VoucherNumber { get; set; }
        public string HotelConfirmation { get; set; }
        public string AccountFileNumber { get; set; }
        public string HotelOD { get; set; }
        public string ClientOD { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> ReservationTypeID { get; set; }
        public Nullable<int> ReservationStatusID { get; set; }
        public string ClientRemarks { get; set; }
        public string HotelRemarks { get; set; }
        public string AgentRemarks { get; set; }
        public Nullable<int> HotelPaymentTypeID { get; set; }
        public Nullable<int> ClientPaymentTypeID { get; set; }
        public string DocumentNumber { get; set; }
        public int OperatorCustomerID { get; set; }
        public Nullable<int> OperatorAgentID { get; set; }
        public string HotelReserveNumber { get; set; }
        public string WebReserveNumber { get; set; }
        public string BankNumber { get; set; }
        public string ClientNumber { get; set; }
        public Nullable<bool> PostToAccount { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public bool HasJV { get; set; }
        public Nullable<System.TimeSpan> HotelOT { get; set; }
        public Nullable<System.TimeSpan> ClientOT { get; set; }
        public Nullable<int> CancellationReasonsID { get; set; }
        public Nullable<System.DateTime> HotelOptionDateTime { get; set; }
        public Nullable<System.DateTime> ClientOptionDateTime { get; set; }
        public string PassportNumber { get; set; }
        public string GeneratedImageName { get; set; }
        public string PassportImageName { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public string JvDescription { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual ReservationStatus ReservationStatus { get; set; }
    }
}
